server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.17.18:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: cathome
  jpa:
    database: mysql
    show-sql: true
  rabbitmq:
    host: 192.168.17.18
    port: 5672
    username: admin
    password: cathome
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
ip: 192.168.17.18.8080
