server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 39.108.53.77
      database: spitdb
  redis:
    host: 39.108.53.77
  rabbitmq:
    host: 39.108.53.77